name: CI

on:
  push:
    braches: [main]
  pull_request:
    braches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repozitory
      uses: actions/chekout@v3

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Running the linter
      run: |
        flake8 .